### ISSUE TITLE
UIWebView has been deprecated

### ISSUE THREAD

**Issue by jeremiahogutu** [particle-iot/particle-photon-setup-ios#14]
I am using the particle setup in my ios app and upon submission to app store. I recieved the following error.

![uiwebview](https://user-images.githubusercontent.com/28146531/78949051-61a45a00-7a98-11ea-9065-a0d8cc87413a.png)

I did a quick search in xcode and found references to UIWebView in ParticleSetupWebViewController. See below.

![UIWebViewParticle](https://user-images.githubusercontent.com/28146531/78949685-4a666c00-7a9a-11ea-93b7-47981d328fad.png)

Any way to update this?

**Comment by RaimundasSakalauskas** [comment]
This has been fixed in 1.0.4 release. Thank you for reporting. https://github.com/particle-iot/particle-photon-setup-ios/releases/tag/1.0.4
