### ISSUE TITLE
particleSetupWebviewController still referencing deprecated api

### ISSUE THREAD

**Issue by jeremiahogutu** [particle-iot/particle-photon-setup-ios#16]
Hello Thank you for updating the Afn networking dependency, we greatly appreciate it. However there is still an issue with the particle-photon-setup-ios repo. If you go to the particleSetupWebviewController.m there is still reference to the deprecated uiwebview. I have attached an image below

![uiwebview_two](https://user-images.githubusercontent.com/28146531/80511167-bde8f400-8949-11ea-9673-907619199bef.png)

**Comment by RaimundasSakalauskas** [comment]
This is now fixed in 1.0.5 release: https://github.com/particle-iot/particle-photon-setup-ios/releases/tag/1.0.5.

Please note that WebView no longer scales the content, so please make sure it renders properly.
